language:      ruby
cache:         bundler
script:
  - "bundle exec rspec spec"
  - "bundle exec bundle-audit check --update"
  - "bundle exec rubocop"
  - "bundle exec brakeman --quiet"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable