language:      ruby
cache:         bundler
env:
  - TEST_SUITE=controllers
  - TEST_SUITE=models
script:
  - "bundle exec rake spec:$TEST_SUITE"
  - "bundle exec bundle-audit check --update"
  - "bundle exec rubocop"
  - "bundle exec brakeman --quiet"
  env:
  - TEST_SUITE=controllers
  - TEST_SUITE=models
